  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: app11-ing
    namespace: websites
    annotations:
       nginx.ingress.kubernetes.io/ssl-redirect: "false"
  spec:
    ingressClassName: nginx
    rules:
      - host: app.MY_DOMAIN
        http:
          paths:
            - pathType: Prefix
              backend:
                service:
                  name: app01-svc 
                  port:
                    number: 8080
              path: /
    # This section is only required if TLS is to be enabled for the Ingress
    tls:
      - hosts:
        - app11.MY_DOMAIN
        secretName: wildcard-tls
