#cloud-config
package_update: true
package_upgrade: true

packages:
  - apache2
  - php
  - php-fpm 
  - haproxy
  - nginx

runcmd:
  - systemctl start httpd
  - systemctl enable httpd
  - echo "<h1>Apache, haproxy, nginx  & PHP  installed via cloud-init</h1>" > /var/www/html/index.html
