# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wilcard
spec:
  secretName: wildcard-tls
  revisionHistoryLimit: 1
  privateKey:
    rotationPolicy: Always
  commonName: "*.MY_DOMAIN"
  dnsNames:
    - "*.MY_DOMAIN"
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
